services:
  acceptor:
    build:
      context: .
      dockerfile: ./acceptor/Dockerfile
      args:
        WORKING_DIR: ${WORKING_DIR}
        APP_PORT: ${APP_PORT}
    restart: unless-stopped
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - APP_PORT=${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - quickfix
  
  initiator:
    build:
      context: .
      dockerfile: ./initiator/Dockerfile
      args:
        WORKING_DIR: ${WORKING_DIR}
    depends_on:
      acceptor:
        condition: service_started
    restart: unless-stopped
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - APP_PORT=${APP_PORT}
    links:
      - acceptor
    networks:
      - quickfix

networks:
  quickfix:


  
