
version: '3'

services:
  acceptor:
    build:
      context: .
      dockerfile: ./acceptor/Dockerfile
    restart: always
    volumes:
      - ./acceptor:${WORKING_DIR}
    command:
      - ${WORKING_DIR}/start.sh
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - quickfix
  
  initiator:
    build:
      context: .
      dockerfile: ./initiator/Dockerfile
    restart: always
    volumes:
      - ./initiator:${WORKING_DIR}
    command:
      - ${WORKING_DIR}/start.sh
    stdin_open: true
    tty: true
    env_file:
      - .env
    links:
      - acceptor
    networks:
      - quickfix

networks:
  quickfix:


  
